sudo: required
services:
    - docker

before_install:
    - docker build -t aneeshsaripalli/client-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true aneeshsaripalli/client-test npm test -- --coverage

after_success:
    - docker build -t aneeshsaripalli/multi-client ./client
    - docker build -t aneeshsaripalli/multi-nginx ./nginx
    - docker build -t aneeshsaripalli/multi-server ./server
    - docker build -t aneeshsaripalli/multi-worker ./worker
    # login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push aneeshsaripalli/multi-client
    - docker push aneeshsaripalli/multi-nginx
    - docker push aneeshsaripalli/multi-server
    - docker push aneeshsaripalli/multi-worker
    